[project]
name = "quick_count"

[ruby]
enabled = true

[ruby.rubocop]
enabled = true
config = ".rubocop.yml"

[coverage]
threshold = 80.0

[quality]
threshold = 8.0

[ignores]
# Ignore generated files and vendor directories
patterns = [
  "coverage/**/*",
  "pkg/**/*",
  "vendor/**/*",
  "spec/support/rails/**/*",
  "gemfiles/**/*"
]